# docker-compose.yml
services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=flask_api.py
      - FLASK_ENV=production
      # PostgreSQL 연결 문자열 (Flask 앱에서 DATABASE_URL 환경변수를 사용하도록 코드 수정 필요)
      - DATABASE_URL=postgresql://postgres:postgres_password@db:5432/mvp_dashboard

    depends_on:
      - db
    volumes:
      - .:/app  # 개발 시 코드 변경 사항이 즉시 반영되도록 (개발 환경에서 사용)
  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_DB=mvp_dashboard
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
